name: CICD
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Install npm electron
        run: |
          npm install --save-dev @electron-forge/cli
          npx electron-forge import
      - name: Create distributable package
        run: npm run make
      - name: List
        run: |
          ls -la
          pwd
