name: CICD
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Install npm electron
        run: |
          npm install --save-dev @electron-forge/cli
          npx electron-forge import
      - name: Create distributable package
        run: npm run make
      - name: List
        run: |
          ls out/make
          echo 1
          ls out/
          echo 2
          ls out/my-electron-app-darwin-x64/my-electron-app.app/Contents/MacOS/
          echo 3
          ls out/my-electron-app-darwin-x64/my-electron-app.app/Contents/
          echo 4
          ls out/my-electron-app-darwin-x64/my-electron-app.app/
          echo 5 
          ls out/make/zip/darwin/x64/
          echo 6
          ls out/make/zip
