name: CICD
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Install npm electron
        run: |
          npm install --save-dev @electron-forge/cli
          npx electron-forge import
          
      - name: Create distributable package
        run: npm run make
        
      - name: Upload app artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: mac-app
          path: out/my-electron-app-darwin-x64/my-electron-app.app/Contents/MacOS/
          
  build_on_wind:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Install npm electron
        run: |
          npm install --save-dev @electron-forge/cli
          npx electron-forge import
          
      - name: Create distributable package
        run: npm run make
        
      - name: Upload app artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: win-app
          path: out\my-electron-app-win32-x64



